# Generated by Django 3.2.16 on 2025-02-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0005_alter_icecream_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecream',
            name='price',
        ),
    ]
